whitelist_rules:
  - closure_end_indentation
  - closure_spacing
  - colon
  - control_statement
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - fatal_error_message
  - force_try
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - vertical_whitespace
  - void_return
  - unused_optional_binding
  - custom_rules
  
excluded:
  - Carthage
  - Pods

colon:
  apply_to_dictionaries: false

indentation: 2

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error